### ISSUE TITLE
Load/unload module for specific Composable function.

### ISSUE THREAD

**Issue by Festak** [burnoo/cokoin#5]
I couldn't understand how to load/unload the koin module for a specific composable function.
Let's say I have a view model injection inside the composable.

Instead of loading all the modules in the Application file, I want to load/unload only the related view model module with its use cases and etc only inside the specific Composable function.

**Comment by burnoo** [comment]
You can wrap ech of your composables with `@Composable Koin()`:
```kotlin
@Composeable
fun Screen1() {
    Koin(appDeclaration = { modules(module1) }) {
        //...
    }
}

@Composeable
fun Screen2() {
    Koin(appDeclaration = { modules(module2) }) {
        //...
    }
}
```
