### ISSUE TITLE
SavedStateProvider with the given key is already registered

### ISSUE THREAD

**Issue by mjalijani** [burnoo/cokoin#6]
this error is related to this [link](https://github.com/InsertKoinIO/koin/issues/1207)
it will be fixed when Koin upgrades to 3.2.0

**Comment by thadcodes** [comment]
Saw this reference.   FYI I just commented on that issue with a fix, however this issue is likely masking another issue with the definitions not loading is likely not the real issue.

**Comment by burnoo** [comment]
Is this still happening in `0.3.4`? I've updated Koin to `3.2.0`

**Comment by mjalijani** [comment]
after upgrading to 0.3.4, syncing failed cause of `Failed to resolve: org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev753`

**Comment by mjalijani** [comment]
after upgrading to 0.3.4, syncing failed cause of `Failed to resolve: org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev753`

**Comment by burnoo** [comment]
It looks like JetBrains didn't upload the newest Compose version to Maven Central (`1.2.0-alpha01-dev753`), as a temporary solution you could add JetBrains maven to buildscript block (should be in `./build.gradle(.kts)` or `./settings.gradle(.kts)`)
```kotlin
buildscript {
    repositories {
        google()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev") // HERE
    }
}
```

**Comment by burnoo** [comment]
Version `1.0.0` is using stable version of Compose Multiplatform (`1.2.0`), so adding JetBrains' maven is no longer necessary
